### ISSUE TITLE
pages without proper panel ads raise error

### ISSUE THREAD

**Issue by austinulfers** [austinulfers/youtube-ad-research#10]
## Error
```
Traceback (most recent call last):
  File "c:/Users/austi/OneDrive/git-projects/youtube-ad-research/src/scrape.py", line 98, in <module>
    ad_metrics = get_metrics(driver, 'ad')
  File "c:/Users/austi/OneDrive/git-projects/youtube-ad-research/src/scrape.py", line 41, in get_metrics
    "title" : BeautifulSoup(driver.find_element_by_class_name('ytp-flyout-cta-headline').get_attribute('outerHTML'), features = "lxml").getText(),
  File "C:\Users\austi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\austi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\austi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\austi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".ytp-flyout-cta-headline"}
  (Session info: chrome=78.0.3904.108)
```
## Solution
Allow for NULL values to be inputted into the `ad_metrics` dict

**Comment by austinulfers** [comment]
`panel_ad_title` will default to `"NULL"` if no value is found.
